env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[!0a7368e23125656a6e2c6d0c12edefb713df6867ce5fec4ea90975d38f7e8e8a00be6adc93b1cfc69dec154bd47e640b!]"
  TG_TOKEN: "ENCRYPTED[!aa0996a6fd7ba78ede94f5d440725f2433b5f90d00f42ab74de742ad9bec24e728d7c88380c4af469ae59129d04c2829!]"
  TG_CHAT_ID: "ENCRYPTED[!b0d9132b656420c006a6a88b3f920a5f80625aae6502958201cf1e5b622abb716c5a2fa72a04f29b1f011e6ab7aabdbd!]"
  SSH_KEY: "ENCRYPTED[!5e625c41487a56ea8ec048bf0ff65f26b47c6454d01b6dab365b47b93942142e60f0292f829320a2a9a7c2b026340387!]"
  PUB_KEY: "ENCRYPTED[!87818a49f5266f9472f7b7103348fa798aa52390580b3a70843b3b9c6894ef1998ef82f27bcf9e35c5e3b31e14ba6282!]"
  KNOWN_HOSTS: "ENCRYPTED[!cfab106cd7d0bb7ef4ede12532cf72ea1216af9739b78d7cfe887dd523323b0df37edbe8c5f5bfb6178d58956b1ea59b!]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "DerpFest 12 Build"
  stateful: true
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_script:
     - ./script/load_ccache.sh

  Repo-pribadi_script:
     - git config --global user.name "Mocarafee"
     - git config --global user.email "harif.rp05@gmail.com"
     - ./script/esesha.sh

  Sinkronasi-rom_script:
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Start sync Source"
     - ./script/sync.sh
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sync Completed!"
     
  Membangun-rom_script:
     - ./script/building.sh
     
  Ccache-informasi_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Mengunggah-build_script:
     - ./script/ziping.sh
