env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[!759c89523d6d9895dc9816e36d03e0427f0ace066a3f43049f30b40bb7653c0c69328eef49753360909cc803034cf086!]"
  TG_TOKEN: "ENCRYPTED[!aa0996a6fd7ba78ede94f5d440725f2433b5f90d00f42ab74de742ad9bec24e728d7c88380c4af469ae59129d04c2829!]"
  TG_CHAT_ID: "ENCRYPTED[!b0d9132b656420c006a6a88b3f920a5f80625aae6502958201cf1e5b622abb716c5a2fa72a04f29b1f011e6ab7aabdbd!]"
  SSH_KEY: "ENCRYPTED[!5e625c41487a56ea8ec048bf0ff65f26b47c6454d01b6dab365b47b93942142e60f0292f829320a2a9a7c2b026340387!]"
  PUB_KEY: "ENCRYPTED[!87818a49f5266f9472f7b7103348fa798aa52390580b3a70843b3b9c6894ef1998ef82f27bcf9e35c5e3b31e14ba6282!]"
  KNOWN_HOSTS: "ENCRYPTED[!bd9d49618ebe575dbc986c6f5c69144d94ea1a9ef7c0f0cc84daa84d1cc82b72e6d21682a26559384f255c891bfd2c34!]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Qassa Build Mido 4.9"
  stateful: true
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_background_script:
     - ./script/load_ccache.sh

  Repo-pribadi_script:
     - git config --global user.name "mocarafee"
     - git config --global user.email "harif.rp05@gmail.com"
     - ./script/esesha.sh

  Sinkronasi-rom_script:
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Start sync Source"
     - ./script/sync.sh
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sync Completed!"
     
  Membangun-rom_script:
     - ./script/building.sh
     
  Ccache-informasi_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Mengunggah-build_script:
     - ./script/ziping.sh
